name: pull_to_refresh_next
description: a widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 1.0.0
homepage: https://github.com/raintyyek/flutter_pulltorefresh

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
